/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import Controller.LoginController;
import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author hnd
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        setTitle("Sunrise Dental - Login");
        setIconImage(new javax.swing.ImageIcon(
                getClass().getResource("/assets/medical-cross.png")).getImage());
        getRootPane().setDefaultButton(jButton1);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblMessage = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<String>();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(36, 115, 66));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("User Name");

        jLabel2.setText("Password");

        lblMessage.setForeground(new java.awt.Color(160, 45, 45));
        lblMessage.setText(" ");
        lblRole.setText("Role");
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<String>(
                new String[] { "Select role", "Staff", "Dentist" }));
        lblTitle.setForeground(new java.awt.Color(36, 115, 66));
        lblTitle.setText("Sunrise Dental");
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblRole))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtPassword)
                            .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addComponent(lblMessage)
                            .addComponent(jButton1))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addGap(16, 16, 16)
                .addComponent(lblMessage)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLogin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final String username = txtUsername.getText();
        final String password = new String(txtPassword.getPassword());
        final String role = (String) cmbRole.getSelectedItem();
        final LoginController controller = new LoginController();
        String result = controller.validateInput(username, password, role);

        if (!result.equals("VALID")) {
            lblMessage.setForeground(new java.awt.Color(160, 45, 45));
            lblMessage.setText(result);
            return;
        }

        jButton1.setEnabled(false);
        txtUsername.setEnabled(false);
        txtPassword.setEnabled(false);
        cmbRole.setEnabled(false);
        lblMessage.setForeground(new java.awt.Color(36, 115, 66));
        lblMessage.setText("Signing in...");

        new javax.swing.SwingWorker<String, Void>() {
            protected String doInBackground() {
                return controller.login(username, password, role);
            }

            protected void done() {
                jButton1.setEnabled(true);
                txtUsername.setEnabled(true);
                txtPassword.setEnabled(true);
                cmbRole.setEnabled(true);
                txtPassword.setText("");
                try {
                    showLoginResult(get(), controller.getAuthenticatedUser());
                } catch (Exception e) {
                    showLoginResult("LOGIN_ERROR", null);
                }
            }
        }.execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showLoginResult(String result, User user) {
        if ("LOGIN_SUCCESS".equals(result)) {
            String role = "STAFF".equals(user.getUserType()) ? "Staff" : "Dentist";
            lblMessage.setForeground(new java.awt.Color(36, 115, 66));
            lblMessage.setText("Login successful.");
            JOptionPane.showMessageDialog(this,
                    "Welcome, " + user.getName() + ".\nSigned in as " + role + ".",
                    "Login successful", JOptionPane.INFORMATION_MESSAGE);
            new MainView(user).setVisible(true);
            dispose();
            return;
        }

        lblMessage.setForeground(new java.awt.Color(160, 45, 45));
        if ("INVALID_CREDENTIALS".equals(result)) {
            lblMessage.setText("Incorrect username or password.");
        } else if ("ROLE_MISMATCH".equals(result)) {
            lblMessage.setText("Selected role does not match this account.");
        } else if ("DATABASE_ERROR".equals(result)) {
            lblMessage.setText("Database unavailable. Please try again.");
        } else {
            lblMessage.setText("Unable to sign in. Please try again.");
        }
        pack();
        txtPassword.requestFocusInWindow();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel lblRole;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlLogin;
    // End of variables declaration//GEN-END:variables
}
